onboarding = false

[keys]
previous_workspace = "prefix+up"
next_workspace = "prefix+down"
switch_workspace = "prefix+shift+1..9"
last_pane = "prefix+o"

[ui]
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true
confirm_close = true

[ui.toast]
delivery = "system"

[ui.sidebar.agents]
rows = [["state_icon", "workspace", "tab"], ["terminal_title_stripped"]]

[experimental]
switch_ascii_input_source_in_prefix = false
pane_history = false

[[keys.command]]
key = "prefix+shift+g"
type = "popup"
command = "env GIT_CONFIG_PARAMETERS='status.showUntrackedFiles=all' lazygit"
description = "run lazygit"
width = "95%"
height = "95%"

[[keys.command]]
key = "prefix+u"
type = "shell"
command = "~/.config/herdr/scripts/herdr-switch.sh"
