#!/bin/zsh

ln -fs "$HOME/dotfiles/.config/aerospace/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/mise/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/nix/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/nvim/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/sheldon/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/starship.toml" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/wezterm/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/zabrze/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/zed/keymap.json" "$HOME/.config/zed/keymap.json"
ln -fs "$HOME/dotfiles/.config/zed/settings.json" "$HOME/.config/zed/settings.json"
ln -fs "$HOME/dotfiles/.gitconfig" "$HOME/.gitconfig"
ln -fs "$HOME/dotfiles/.ideavimrc" "$HOME/.ideavimrc"
ln -fs "$HOME/dotfiles/.latexmkrc" "$HOME/.latexmkrc"
ln -fs "$HOME/dotfiles/.vimrc" "$HOME/.vimrc"
ln -fs "$HOME/dotfiles/.vscode/keybindings.json" "$HOME/Library/Application Support/Code/User/keybindings.json"
ln -fs "$HOME/dotfiles/.vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
ln -fs "$HOME/dotfiles/.vscode/tasks.json" "$HOME/Library/Application Support/Code/User/tasks.json"
ln -fs "$HOME/dotfiles/.zshenv" "$HOME/.zshenv"
ln -fs "$HOME/dotfiles/.zshrc" "$HOME/.zshrc"
