#!/bin/zsh

ln -fs "$HOME/dotfiles/.zshrc" "$HOME/.zshrc"
ln -fs "$HOME/dotfiles/.zshenv" "$HOME/.zshenv"
ln -fs "$HOME/dotfiles/.vimrc" "$HOME/.vimrc"
ln -fs "$HOME/dotfiles/.ideavimrc" "$HOME/.ideavimrc"
ln -fs "$HOME/dotfiles/.config/aerospace/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/mise/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/nix/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/nvim/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/sheldon/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/wezterm/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/starship.toml" "$HOME/.config"
ln -fs "$HOME/dotfiles/.config/zabrze/" "$HOME/.config"
ln -fs "$HOME/dotfiles/.gitconfig" "$HOME/.gitconfig"
ln -fs "$HOME/dotfiles/.latexmkrc" "$HOME/.latexmkrc"
