shell = "zsh"

[plugins.zsh-defer]
apply = ["source"]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-autosuggestions]
apply = ["defer"]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
apply = ["defer"]
github = "zsh-users/zsh-completions"

[plugins.zsh-syntax-highlighting]
apply = ["defer"]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.z]
apply = ["defer"]
github = "rupa/z"

[plugins.zsh-history-substring-search]
apply = ["defer"]
github = "zsh-users/zsh-history-substring-search"

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.zabrze]
inline = 'eval "$(zabrze init --bind-keys)"'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
