[[snippets]]
name = "cd .."
trigger = ".."
snippet = "cd .."

[[snippets]]
name = "cd ../.."
trigger = "..."
snippet = "cd ../.."

[[snippets]]
name = "cd ../../.."
trigger = "...."
snippet = "cd ../../.."

[[snippets]]
name = "cd ../../../.."
trigger = "....."
snippet = "cd ../../../.."
