abbrevs:
  # cd abbreviations
  - name: cd ..
    abbr: ..
    snippet: cd ..

  - name: cd ../..
    abbr: ...
    snippet: cd ../..

  - name: cd ../../..
    abbr: ....
    snippet: cd ../../..

  - name: cd ../../../..
    abbr: .....
    snippet: cd ../../../..

  # git abbreviations
  - name: git
    abbr: g
    snippet: git

  - name: git add
    abbr: ga
    snippet: git add

  - name: git commit
    abbr: gc
    snippet: git commit

  - name: git push
    abbr: gp
    snippet: git push

  - name: git pull
    abbr: gpl
    snippet: git pull

  - name: git status
    abbr: gs
    snippet: git status

  - name: git log
    abbr: gl
    snippet: git log

  - name: git branch
    abbr: gb
    snippet: git branch

  - name: git switch
    abbr: gsw
    snippet: git switch

  - name: git diff
    abbr: gd
    snippet: git diff

  - name: git merge
    abbr: gm
    snippet: git merge

  - name: git restore
    abbr: gr
    snippet: git restore

  - name: git reset
    abbr: grs
    snippet: git reset

  - name: git clone
    abbr: gcl
    snippet: git clone

  - name: git remote
    abbr: grm
    snippet: git remote

  - name: git stash
    abbr: gst
    snippet: git stash

  - name: git rebase
    abbr: grb
    snippet: git rebase

  - name: git cz --disable-emoji
    abbr: gcz
    snippet: git cz --disable-emoji

  # docker abbreviations
  - name: docker
    abbr: d
    snippet: docker

  - name: docker ps
    abbr: dp
    snippet: docker ps

  - name: docker images
    abbr: di
    snippet: docker images

  - name: docker exec
    abbr: de
    snippet: docker exec

  - name: docker compose build
    abbr: dcb
    snippet: docker compose build

  - name: docker compose stop
    abbr: dcs
    snippet: docker compose stop

  - name: docker compose up
    abbr: dcu
    snippet: docker compose up

  - name: docker compose down
    abbr: dcd
    snippet: docker compose down

  - name: docker compose logs
    abbr: dcl
    snippet: docker compose logs

  - name: docker compose ps
    abbr: dcp
    snippet: docker compose ps

  - name: docker compose exec
    abbr: dce
    snippet: docker compose exec

  # neovim abbreviations
  - name: nvim
    abbr: vim
    snippet: nvim

  - name: nvim
    abbr: vi
    snippet: nvim

  # reload abbreviations
  - name: source ~/.zshrc
    abbr: reload
    snippet: source ~/.zshrc
