#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "yutanishi"
email = "ypmtk437.0209@gmail.com"

[diff]
tool = "delta"

[ui]
pager = "delta"
diff-formatter = ":git"
default-command = "log"
editor = "vim"
