[tools]
bun = "latest"
deno = "latest"
go = "latest"
java = "21"     # LTS
# To avoid vscode neovim crash
# see: https://github.com/vscode-neovim/vscode-neovim/issues/2184
neovim = "0.9"
node = "22"     # LTS
pnpm = "latest"
python = "3.11" # LTS
ruby = "latest"
