[tools]
bun = "latest"
deno = "latest"
go = "latest"
java = "21"       # LTS
neovim = "latest"
node = "22"       # LTS
"npm:@antfu/ni" = "latest"
"npm:pnpm" = "latest"
python = "3.12"   # LTS
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = []
