[tools]
bun = "latest"
deno = "latest"
go = "latest"
java = "21"           # LTS
neovim = "latest"
node = "22"           # LTS
"npm:pnpm" = "latest"
python = "3.11"       # LTS
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = []
